[tool.poetry]
name = "scrape-test"
version = "0.1.0"
description = ""
authors = ["Morshues Lai <ml@discoverelement.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
shot-scraper = "^1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
